//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v2beta2 "k8s.io/api/autoscaling/v2beta2"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoResourceExpansion) DeepCopyInto(out *AutoResourceExpansion) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoResourceExpansion.
func (in *AutoResourceExpansion) DeepCopy() *AutoResourceExpansion {
	if in == nil {
		return nil
	}
	out := new(AutoResourceExpansion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNodeResourcePolicy) DeepCopyInto(out *ClusterNodeResourcePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNodeResourcePolicy.
func (in *ClusterNodeResourcePolicy) DeepCopy() *ClusterNodeResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterNodeResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterNodeResourcePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNodeResourcePolicyList) DeepCopyInto(out *ClusterNodeResourcePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterNodeResourcePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNodeResourcePolicyList.
func (in *ClusterNodeResourcePolicyList) DeepCopy() *ClusterNodeResourcePolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterNodeResourcePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterNodeResourcePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNodeResourcePolicySpec) DeepCopyInto(out *ClusterNodeResourcePolicySpec) {
	*out = *in
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(NodeResourcePolicyTemplate)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNodeResourcePolicySpec.
func (in *ClusterNodeResourcePolicySpec) DeepCopy() *ClusterNodeResourcePolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterNodeResourcePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterNodeResourcePolicyStatus) DeepCopyInto(out *ClusterNodeResourcePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterNodeResourcePolicyStatus.
func (in *ClusterNodeResourcePolicyStatus) DeepCopy() *ClusterNodeResourcePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterNodeResourcePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CraneSchedulerConfiguration) DeepCopyInto(out *CraneSchedulerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CraneSchedulerConfiguration.
func (in *CraneSchedulerConfiguration) DeepCopy() *CraneSchedulerConfiguration {
	if in == nil {
		return nil
	}
	out := new(CraneSchedulerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CraneSchedulerConfigurationSpec) DeepCopyInto(out *CraneSchedulerConfigurationSpec) {
	*out = *in
	in.ScheduleApplyScope.DeepCopyInto(&out.ScheduleApplyScope)
	in.SchedulePolicy.DeepCopyInto(&out.SchedulePolicy)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CraneSchedulerConfigurationSpec.
func (in *CraneSchedulerConfigurationSpec) DeepCopy() *CraneSchedulerConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(CraneSchedulerConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPredicateScheduleRule) DeepCopyInto(out *DefaultPredicateScheduleRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPredicateScheduleRule.
func (in *DefaultPredicateScheduleRule) DeepCopy() *DefaultPredicateScheduleRule {
	if in == nil {
		return nil
	}
	out := new(DefaultPredicateScheduleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultPriorityScheduleRule) DeepCopyInto(out *DefaultPriorityScheduleRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultPriorityScheduleRule.
func (in *DefaultPriorityScheduleRule) DeepCopy() *DefaultPriorityScheduleRule {
	if in == nil {
		return nil
	}
	out := new(DefaultPriorityScheduleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpressionPredicateScheduleRule) DeepCopyInto(out *ExpressionPredicateScheduleRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpressionPredicateScheduleRule.
func (in *ExpressionPredicateScheduleRule) DeepCopy() *ExpressionPredicateScheduleRule {
	if in == nil {
		return nil
	}
	out := new(ExpressionPredicateScheduleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpressionPriorityScheduleRule) DeepCopyInto(out *ExpressionPriorityScheduleRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpressionPriorityScheduleRule.
func (in *ExpressionPriorityScheduleRule) DeepCopy() *ExpressionPriorityScheduleRule {
	if in == nil {
		return nil
	}
	out := new(ExpressionPriorityScheduleRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotValueMetric) DeepCopyInto(out *HotValueMetric) {
	*out = *in
	if in.HotValueWeights != nil {
		in, out := &in.HotValueWeights, &out.HotValueWeights
		*out = make([]HotValueWeight, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotValueMetric.
func (in *HotValueMetric) DeepCopy() *HotValueMetric {
	if in == nil {
		return nil
	}
	out := new(HotValueMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotValueWeight) DeepCopyInto(out *HotValueWeight) {
	*out = *in
	out.TimeRange = in.TimeRange
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotValueWeight.
func (in *HotValueWeight) DeepCopy() *HotValueWeight {
	if in == nil {
		return nil
	}
	out := new(HotValueWeight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSyncPolicy) DeepCopyInto(out *MetricSyncPolicy) {
	*out = *in
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = make(map[string]v1.Duration, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GenHotValueMetric != nil {
		in, out := &in.GenHotValueMetric, &out.GenHotValueMetric
		*out = new(HotValueMetric)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSyncPolicy.
func (in *MetricSyncPolicy) DeepCopy() *MetricSyncPolicy {
	if in == nil {
		return nil
	}
	out := new(MetricSyncPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceSelector) DeepCopyInto(out *NamespaceSelector) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceSelector.
func (in *NamespaceSelector) DeepCopy() *NamespaceSelector {
	if in == nil {
		return nil
	}
	out := new(NamespaceSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourcePolicy) DeepCopyInto(out *NodeResourcePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourcePolicy.
func (in *NodeResourcePolicy) DeepCopy() *NodeResourcePolicy {
	if in == nil {
		return nil
	}
	out := new(NodeResourcePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourcePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourcePolicyList) DeepCopyInto(out *NodeResourcePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeResourcePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourcePolicyList.
func (in *NodeResourcePolicyList) DeepCopy() *NodeResourcePolicyList {
	if in == nil {
		return nil
	}
	out := new(NodeResourcePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeResourcePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourcePolicySpec) DeepCopyInto(out *NodeResourcePolicySpec) {
	*out = *in
	if in.TargetRef != nil {
		in, out := &in.TargetRef, &out.TargetRef
		*out = new(v2beta2.CrossVersionObjectReference)
		**out = **in
	}
	if in.StaticResourceExpansion != nil {
		in, out := &in.StaticResourceExpansion, &out.StaticResourceExpansion
		*out = new(StaticResourceExpansion)
		(*in).DeepCopyInto(*out)
	}
	if in.AutoResourceExpansion != nil {
		in, out := &in.AutoResourceExpansion, &out.AutoResourceExpansion
		*out = new(AutoResourceExpansion)
		**out = **in
	}
	if in.EvictLoadThreshold != nil {
		in, out := &in.EvictLoadThreshold, &out.EvictLoadThreshold
		*out = new(Threshold)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetLoadThreshold != nil {
		in, out := &in.TargetLoadThreshold, &out.TargetLoadThreshold
		*out = new(Threshold)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourcePolicySpec.
func (in *NodeResourcePolicySpec) DeepCopy() *NodeResourcePolicySpec {
	if in == nil {
		return nil
	}
	out := new(NodeResourcePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourcePolicyStatus) DeepCopyInto(out *NodeResourcePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourcePolicyStatus.
func (in *NodeResourcePolicyStatus) DeepCopy() *NodeResourcePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(NodeResourcePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourcePolicyTemplate) DeepCopyInto(out *NodeResourcePolicyTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourcePolicyTemplate.
func (in *NodeResourcePolicyTemplate) DeepCopy() *NodeResourcePolicyTemplate {
	if in == nil {
		return nil
	}
	out := new(NodeResourcePolicyTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSelector) DeepCopyInto(out *PodSelector) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSelector.
func (in *PodSelector) DeepCopy() *PodSelector {
	if in == nil {
		return nil
	}
	out := new(PodSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredicatePolicy) DeepCopyInto(out *PredicatePolicy) {
	*out = *in
	if in.DefaultScheduleRule != nil {
		in, out := &in.DefaultScheduleRule, &out.DefaultScheduleRule
		*out = new(DefaultPredicateScheduleRule)
		**out = **in
	}
	if in.ExpressionScheduleRule != nil {
		in, out := &in.ExpressionScheduleRule, &out.ExpressionScheduleRule
		*out = new(ExpressionPredicateScheduleRule)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredicatePolicy.
func (in *PredicatePolicy) DeepCopy() *PredicatePolicy {
	if in == nil {
		return nil
	}
	out := new(PredicatePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriorityPolicy) DeepCopyInto(out *PriorityPolicy) {
	*out = *in
	if in.DefaultScheduleRule != nil {
		in, out := &in.DefaultScheduleRule, &out.DefaultScheduleRule
		*out = new(DefaultPriorityScheduleRule)
		**out = **in
	}
	if in.ExpressionScheduleRule != nil {
		in, out := &in.ExpressionScheduleRule, &out.ExpressionScheduleRule
		*out = new(ExpressionPriorityScheduleRule)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriorityPolicy.
func (in *PriorityPolicy) DeepCopy() *PriorityPolicy {
	if in == nil {
		return nil
	}
	out := new(PriorityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleApplyScope) DeepCopyInto(out *ScheduleApplyScope) {
	*out = *in
	if in.NamespaceScopeSelector != nil {
		in, out := &in.NamespaceScopeSelector, &out.NamespaceScopeSelector
		*out = new(NamespaceSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PodScopeSelector != nil {
		in, out := &in.PodScopeSelector, &out.PodScopeSelector
		*out = new([]PodSelector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]PodSelector, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleApplyScope.
func (in *ScheduleApplyScope) DeepCopy() *ScheduleApplyScope {
	if in == nil {
		return nil
	}
	out := new(ScheduleApplyScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulePolicy) DeepCopyInto(out *SchedulePolicy) {
	*out = *in
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make(map[string]PredicatePolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Priorities != nil {
		in, out := &in.Priorities, &out.Priorities
		*out = make(map[string]PriorityPolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulePolicy.
func (in *SchedulePolicy) DeepCopy() *SchedulePolicy {
	if in == nil {
		return nil
	}
	out := new(SchedulePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticResourceExpansion) DeepCopyInto(out *StaticResourceExpansion) {
	*out = *in
	if in.Ratios != nil {
		in, out := &in.Ratios, &out.Ratios
		*out = make(map[corev1.ResourceName]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticResourceExpansion.
func (in *StaticResourceExpansion) DeepCopy() *StaticResourceExpansion {
	if in == nil {
		return nil
	}
	out := new(StaticResourceExpansion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Threshold) DeepCopyInto(out *Threshold) {
	*out = *in
	if in.Percents != nil {
		in, out := &in.Percents, &out.Percents
		*out = make(map[corev1.ResourceName]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Threshold.
func (in *Threshold) DeepCopy() *Threshold {
	if in == nil {
		return nil
	}
	out := new(Threshold)
	in.DeepCopyInto(out)
	return out
}
